### ISSUE TITLE
Visual Studio 2017 15.8.1, C#, Refactor 'Rename identifier' and 'Change signature' crashes Visual Studio when using StdInput option

### ISSUE THREAD

**Issue by skotten** [marianob85/CodeBeautifier#2]
No crash report to be seen anywhere.

If I disable the beautifier I have configured for C# (uncrustify) the refactoring works.

If I use the File configuration (instead of StdInput), that works too.

CodeBeautifier version 1.1.0.580

The workaround works for me, this is just a FYI.

**Comment by marianob85** [comment]
I will try to fix it with https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration

**Comment by marianob85** [comment]
V 1.4.0.0
