### ISSUE TITLE
semicolon after initializer list falsely removed

### ISSUE THREAD

**Issue by andreasgrueter** [marianob85/CodeBeautifier#5]
Version 1.4.14.0

semicolons after initializer list are falsely removed:

```
std::vector<int> Vector::vector()
{
	auto v = std::vector<int> { 1, 2, 3 };
	return std::vector<int> { 3, 4, 5 };
}
```

**Comment by marianob85** [comment]
CodeBeautifier is a only wrapper tool. Please address such issue to formatting tool that you are using  ( clang-format, uncrustify, etc...

**Comment by andreasgrueter** [comment]
Sorry, my fault
thank you
